name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ main ]


env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:

  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build and push image Aliyun
      run: |
        
        echo "docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY"

        docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY

        while IFS= read -r line; do  
          # 跳过空行  
          [[ -z "$line" ]] && continue  
          
          # 提取repository和tag  
          IFS=':' read -ra parts <<< "$line"  
          repository="${parts[0]}"  
          tag="${parts[1]}"  
          
          # 如果没有指定tag,则默认为latest  
          if [[ -z "$tag" ]]; then  
            tag="latest"  
          fi  
          
          # 构造新的镜像名称  
          # 如果repository中包含/,则保留整个路径作为新的repository名称  
          # 否则,只使用repository作为新的repository名称  
          if [[ "$repository" == */* ]]; then  
            new_repository="${repository#*/}" # 移除开头的/和可能的registry部分  
          else  
            new_repository="$repository"  
          fi  
          new_image="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/$new_repository:$tag"  
          
          echo "docker pull $line"  
          docker pull "$line"  
          echo "docker tag $line $new_image"  
          docker tag "$line" "$new_image"  
          echo "docker push $new_image"  
          docker push "$new_image"  
        done < images.txt
